title: Memoizable
description: > # this means to ignore newlines until "baseurl:"
  Blogs and tutorials on Programming languages, Distributed systems and architecture, Functional programming and much more.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here
text-logo: '{-MEMOIZABLE-}'

# Author Settings
author: Hariharan Viswanathan # add your name
author-img: https://avatars2.githubusercontent.com/u/7565404?s=400&u=cf5879915d2919967214e740195e1d7196fe0682&v=4 # add your photo
about-author: > 
  An avid ployglot Coder with 10 plus years' experience in product and system development. Designed and developed highly scalable, distributed and performant large-scale systems that handle millions of requests every day

  Functional Programming, scalability and Distributed architectures are few of the topics that excites me.

  I live in Bangalore, India. 

# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: hariharanv01 # add your Github handle
social-linkedin: hariharanviswanathan # add your Linkedin handle
social-email: hariharanv01@gmail.com # add your Email address
favicon: memoizable.png #favicon
img-folder: "/assets/img/" #images folder

# Disqus
discus-identifier: hariharanv01 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
